language: rust
rust: 
  - nightly

cache:
  cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-dev
    - clang

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust:   
      - stable
      - beta
 
script:
  - cargo check
    
