language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    
notifications:
  webhooks:
    urls:
      - https://discordhooks.herokuapp.com/travis
    on_success: always
    on_failure: always
    on_start: always
