language: rust
rust: 
  - nightly

cache:
  cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-dev
    - clang

rust: nightly
 
script:
  - cargo check
    
