language: rust
rust: 
  - stable

cache:
  cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-dev
    - clang

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
 
script:
  - cargo build --release
    
notifications:
  webhooks:
    urls:
      - https://discordhooks.herokuapp.com/travis
    on_success: always
    #on_failure: always
    #on_start: always
