[package]
name = "avrio_p2p"
version = "0.1.0"
authors = ["Arielh25 <areilhurdle@gmail.com>", "TheDevMinerTV <tobigames200@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.47"
rand = "0.7"
tokio = { version = "0.2", features = ["full"] }
libp2p = "0.15.0"
