[package]
name = "avrio_database"
version = "0.1.0"
edition = "2018"
authors = ["Leo Cornelius <leocornelius019@gmail.com>"]
license = "MIT OR Apache-2.0"
[dependencies]
serde_json = "1.0.48"
cryptonight-rs = { path = "../crypto/cn-rs"}
hex = "0.4"
